name: Run test manual

on:
  workflow_dispatch

jobs:
  bild:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    - name: Set up python v3.12
      uses:
