name: Run test manual

on:
  workflow_dispatch:

jobs:
  bild:
    runs-on: ubunty-lastest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build -t luma_tests .
    - name: Run the Docker container
      run: docker run luma_tests
