name: Autotested with allure
on:
  workflow_dispatch:
    inputs:
      deployment_target:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkaout repository
        uses: actions/checkout@v4
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: All tests
        run: pytest


